name: Run Cargo Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt
          
      - name: Format code
        run: cargo fmt --all
        
      - name: Check for changes
        id: changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Commit changes
        if: steps.changes.outputs.changes == 'true'
        run: |
            git config --global user.name "$GITHUB_ACTOR"
            git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            git -b checkout cargo-fmt
            git commit -am "Apply cargo fmt changes"
            git push origin HEAD:cargo-fmt --force
        