name: Rust OS Kernel Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-x86

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rust-src, llvm-tools-preview
          
      - name: Install bootimage
        run: cargo install bootimage
        
      - name: Add custom target
        run: |
          mkdir -p ~/.cargo
          echo '[build]' > ~/.cargo/config.toml
          echo 'target = "x86_64-PortfoliOS.json"' >> ~/.cargo/config.toml
          
      - name: Build kernel
        run: cargo build --verbose
        
      - name: Run tests
        run: cargo test --verbose

